# Generated by Django 4.2.1 on 2023-09-14 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='total_likes',
            field=models.PositiveIntegerField(default=0, verbose_name='Общее количество лайков'),
        ),
    ]
