# Generated by Django 4.2.1 on 2023-10-05 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_total_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Информация об пользователе'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Информация об пользователе'),
        ),
    ]
