# Generated by Django 4.2.1 on 2023-12-03 09:10

from django.db import migrations, models
import services.users.validator


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'Пользователь с таким именем уже существует.'}, help_text='Обязательное условие. 150 символов или меньше. Только буквы, цифры, пробелы и @/./+/-/_.', max_length=150, unique=True, validators=[services.users.validator.ImprovedUnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
