# Generated by Django 4.2.1 on 2024-10-30 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_category_description_en_category_description_ru_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-publish', '-id'), 'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-publish', '-id'], name='publish_id_idx'),
        ),
    ]
