# Generated by Django 4.2.1 on 2023-07-04 11:13

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flatpages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Эл. почта')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Телефон')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('feedback', models.BooleanField(default=False, verbose_name='Обрантая связь')),
            ],
            options={
                'verbose_name': 'Запрос',
                'verbose_name_plural': 'Запросы',
            },
        ),
        migrations.CreateModel(
            name='NewFlatpage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='', verbose_name='Основной текстовый контент страницы')),
                ('email_contact', models.EmailField(default='', max_length=254, verbose_name='Эл. почта для контакта')),
                ('phone1_num', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Мобильный телефон')),
                ('phone2_num', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Стационарный телефон')),
                ('flatpage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='flatpages.flatpage')),
            ],
            options={
                'verbose_name': 'Содержание страницы',
                'verbose_name_plural': 'Содержание страницы',
            },
        ),
    ]
