# Generated by Django 4.2.1 on 2023-08-21 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flatpage_contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Запрос от пользователя блога', 'verbose_name_plural': 'Запросы от пользователей блога'},
        ),
    ]
