# Generated by Django 4.2.1 on 2023-10-06 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flatpage_contact', '0002_alter_contact_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='newflatpage',
            name='description_en',
            field=models.TextField(default='', null=True, verbose_name='Основной текстовый контент страницы'),
        ),
        migrations.AddField(
            model_name='newflatpage',
            name='description_ru',
            field=models.TextField(default='', null=True, verbose_name='Основной текстовый контент страницы'),
        ),
    ]
