# Generated by Django 4.2.1 on 2024-01-30 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flatpage_contact', '0003_newflatpage_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newflatpage',
            name='google_maps_html',
            field=models.TextField(default='', verbose_name='HTML-код Google Maps'),
        ),
    ]
